# Generated by Django 3.2.3 on 2021-06-17 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='Customer_account', serialize=False, to='accounts.user')),
                ('image', models.ImageField(upload_to='media/customer/%Y/%m/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='SellerProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='Seller_account', serialize=False, to='accounts.user')),
                ('bio', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='media/Seller/%Y/%m/%d/')),
            ],
        ),
    ]
